language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amqo/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amqo/client-test npm run test

after_success:
  - docker build -t amqo/multi-client ./client
  - docker build -t amqo/multi-nginx ./nginx
  - docker build -t amqo/multi-server ./server
  - docker build -t amqo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Push docker images to docker hub
  - docker push amqo/multi-client
  - docker push amqo/multi-nginx
  - docker push amqo/multi-server
  - docker push amqo/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-660152619074"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
